-- phpMyAdmin SQL Dump
-- version 5.1.1deb5ubuntu1
-- https://www.phpmyadmin.net/
--
-- Host: localhost:3306
-- Generation Time: Feb 02, 2023 at 05:13 PM
-- Server version: 10.6.11-MariaDB-0ubuntu0.22.04.1
-- PHP Version: 8.1.2-1ubuntu2.10

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `ftonini`
--

-- --------------------------------------------------------

--
-- Table structure for table `prodotto`
--

CREATE TABLE `prodotto` (
  `id_prodotto` int(10) NOT NULL,
  `nome` varchar(30) NOT NULL,
  `taglia` varchar(5) DEFAULT NULL,
  `prezzo` int(10) NOT NULL,
  `immagine` varchar(30) NOT NULL,
  `categoria` varchar(20) NOT NULL,
  `stelle` int(1) NOT NULL,
  `alt` text NOT NULL,
  `informazioni` text NOT NULL,
  `keywords` text NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Dumping data for table `prodotto`
--

INSERT INTO `prodotto` (`id_prodotto`, `nome`, `taglia`, `prezzo`, `immagine`, `categoria`, `stelle`, `alt`, `informazioni`, `keywords`) VALUES
(1, 'T-Shirt', '', 20, 't_shirt', 'basic', 0, 'T-shirt bianca', ' \r\n                                    <dt>Materiale:</dt>\r\n                                    <dd>Cotone</dd>\r\n                                  \r\n                                 \r\n                                    <dt lang=\"en\">Fit:</dt>\r\n                                    <dd>Oversize</dd>\r\n                                  \r\n                                 \r\n                                    <dt>Lavaggio:</dt>\r\n                                    <dd>Lavare a mano</dd>\r\n                                  \r\n                                 \r\n                                    <dt>Tipo di manica:</dt>\r\n                                    <dd>Corta</dd>\r\n                                  ', 'maglietta, cotone'),
(2, 'T-shirt Colors', 'XL', 20, 't_shirt_colors', 'T-Shirt', 2, 'maglia con stampa dell’opera Colors', ' \r\n                                    <dt>Materiale:</dt>\r\n                                    <dd>Cotone</dd>\r\n                                  \r\n                                 \r\n                                    <dt lang=\"en\">Fit:</dt>\r\n                                    <dd>Oversize</dd>\r\n                                  \r\n                                 \r\n                                    <dt>Lavaggio:</dt>\r\n                                    <dd>Lavare a mano</dd>\r\n                                  \r\n                                 \r\n                                    <dt>Tipo di manica:</dt>\r\n                                    <dd>Corta</dd>\r\n                                  ', 'maglietta, cotone, personalizzata'),
(3, 'T-shirt Propped', 'S', 20, 't_shirt_propped', 'T-Shirt', 2, 'maglia con stampa dell’opera Propped', ' \r\n                                    <dt>Materiale:</dt>\r\n                                    <dd>Cotone</dd>\r\n                                  \r\n                                 \r\n                                    <dt lang=\"en\">Fit:</dt>\r\n                                    <dd>Oversize</dd>\r\n                                  \r\n                                 \r\n                                    <dt>Lavaggio:</dt>\r\n                                    <dd>Lavare a mano</dd>\r\n                                  \r\n                                 \r\n                                    <dt>Tipo di manica:</dt>\r\n                                    <dd>Corta</dd>\r\n                                  ', 'maglietta, cotone, personalizzata'),
(4, 'T-shirt Migrants', 'S', 20, 't_shirt_migrants', 'T-Shirt', 2, 'maglia con stampa dell’opera Migrants', ' \r\n                                    <dt>Materiale:</dt>\r\n                                    <dd>Cotone</dd>\r\n                                  \r\n                                 \r\n                                    <dt lang=\"en\">Fit:</dt>\r\n                                    <dd>Oversize</dd>\r\n                                  \r\n                                 \r\n                                    <dt>Lavaggio:</dt>\r\n                                    <dd>Lavare a mano</dd>\r\n                                  \r\n                                 \r\n                                    <dt>Tipo di manica:</dt>\r\n                                    <dd>Corta</dd>\r\n                                  ', 'maglietta, cotone, personalizzata'),
(5, 'T-shirt Migrants', 'M', 20, 't_shirt_migrants', 'T-Shirt', 2, 'maglia con stampa dell’opera Migrants', ' \r\n                                    <dt>Materiale:</dt>\r\n                                    <dd>Cotone</dd>\r\n                                  \r\n                                 \r\n                                    <dt lang=\"en\">Fit:</dt>\r\n                                    <dd>Oversize</dd>\r\n                                  \r\n                                 \r\n                                    <dt>Lavaggio:</dt>\r\n                                    <dd>Lavare a mano</dd>\r\n                                  \r\n                                 \r\n                                    <dt>Tipo di manica:</dt>\r\n                                    <dd>Corta</dd>\r\n                                  ', 'maglietta, cotone, personalizzata'),
(6, 'T-shirt Migrants', 'L', 20, 't_shirt_migrants', 'T-Shirt', 2, 'maglia con stampa dell’opera Migrants', ' \r\n                                    <dt>Materiale:</dt>\r\n                                    <dd>Cotone</dd>\r\n                                  \r\n                                 \r\n                                    <dt lang=\"en\">Fit:</dt>\r\n                                    <dd>Oversize</dd>\r\n                                  \r\n                                 \r\n                                    <dt>Lavaggio:</dt>\r\n                                    <dd>Lavare a mano</dd>\r\n                                  \r\n                                 \r\n                                    <dt>Tipo di manica:</dt>\r\n                                    <dd>Corta</dd>\r\n                                  ', 'maglietta, cotone, personalizzata'),
(7, 'Tazza', NULL, 10, 'tazza', 'basic', 0, 'tazza', ' \r\n                                    <dt>Materiale:</dt>\r\n                                    <dd>Ceramica</dd>\r\n                                  \r\n                                 \r\n                                    <dt lang=\"en\">Colore:</dt>\r\n                                    <dd>Bianco</dd>\r\n                                  \r\n                                 \r\n                                    <dt>Capacità:</dt>\r\n                                    <dd>550 <abbr title=\"millilitri\"> ml</abbr></dd>\r\n                                  \r\n                                 \r\n                                    <dt>Caratteristica speciale:</dt>\r\n                                    <dd>Tenuta stagna</dd>\r\n                                  ', 'tazza, ceramica'),
(8, 'Tazza Colors', 'U', 10, 'tazza_colors', 'Tazza', 0, 'tazza con stampa dell’opera Colors', ' \r\n                                    <dt>Materiale:</dt>\r\n                                    <dd>Ceramica</dd>\r\n                                  \r\n                                 \r\n                                    <dt lang=\"en\">Colore:</dt>\r\n                                    <dd>Bianco</dd>\r\n                                  \r\n                                 \r\n                                    <dt>Capacità:</dt>\r\n                                    <dd>550 <abbr title=\"millilitri\"> ml</abbr></dd>\r\n                                  \r\n                                 \r\n                                    <dt>Caratteristica speciale:</dt>\r\n                                    <dd>Tenuta stagna</dd>\r\n                                  ', 'tazza, ceramica, personalizzata'),
(9, 'Tazza Propped', 'U', 10, 'tazza_propped', 'Tazza', 0, 'tazza con stampa dell’opera Propped', ' \r\n                                    <dt>Materiale:</dt>\r\n                                    <dd>Ceramica</dd>\r\n                                  \r\n                                 \r\n                                    <dt lang=\"en\">Colore:</dt>\r\n                                    <dd>Bianco</dd>\r\n                                  \r\n                                 \r\n                                    <dt>Capacità:</dt>\r\n                                    <dd>550 <abbr title=\"millilitri\"> ml</abbr></dd>\r\n                                  \r\n                                 \r\n                                    <dt>Caratteristica speciale:</dt>\r\n                                    <dd>Tenuta stagna</dd>\r\n                                  ', 'tazza, ceramica, personalizzata'),
(10, 'Tazza Migrants', 'U', 10, 'tazza_migrants', 'Tazza', 0, 'tazza bianca', ' \r\n                                    <dt>Materiale:</dt>\r\n                                    <dd>Ceramica</dd>\r\n                                  \r\n                                 \r\n                                    <dt lang=\"en\">Colore:</dt>\r\n                                    <dd>Bianco</dd>\r\n                                  \r\n                                 \r\n                                    <dt>Capacità:</dt>\r\n                                    <dd>550 <abbr title=\"millilitri\"> ml</abbr></dd>\r\n                                  \r\n                                 \r\n                                    <dt>Caratteristica speciale:</dt>\r\n                                    <dd>Tenuta stagna</dd>\r\n                                  ', 'tazza, ceramica, personalizzata'),
(11, 'T-shirt Colors', 'M', 20, 't_shirt_colors', 'T-Shirt', 2, 'maglia con stampa dell’opera Colors', ' \r\n                                    <dt>Materiale:</dt>\r\n                                    <dd>Cotone</dd>\r\n                                  \r\n                                 \r\n                                    <dt lang=\"en\">Fit:</dt>\r\n                                    <dd>Oversize</dd>\r\n                                  \r\n                                 \r\n                                    <dt>Lavaggio:</dt>\r\n                                    <dd>Lavare a mano</dd>\r\n                                  \r\n                                 \r\n                                    <dt>Tipo di manica:</dt>\r\n                                    <dd>Corta</dd>\r\n                                  ', 'maglietta, cotone, personalizzata'),
(12, 'T-shirt Colors', 'L', 20, 't_shirt_colors', 'T-Shirt', 2, 'maglia con stampa dell’opera Colors', ' \r\n                                    <dt>Materiale:</dt>\r\n                                    <dd>Cotone</dd>\r\n                                  \r\n                                 \r\n                                    <dt lang=\"en\">Fit:</dt>\r\n                                    <dd>Oversize</dd>\r\n                                  \r\n                                 \r\n                                    <dt>Lavaggio:</dt>\r\n                                    <dd>Lavare a mano</dd>\r\n                                  \r\n                                 \r\n                                    <dt>Tipo di manica:</dt>\r\n                                    <dd>Corta</dd>\r\n                                  ', 'maglietta, cotone, personalizzata'),
(13, 'T-shirt Colors', 'S', 20, 't_shirt_colors', 'T-Shirt', 2, 'maglia con stampa dell’opera Colors', ' \r\n                                    <dt>Materiale:</dt>\r\n                                    <dd>Cotone</dd>\r\n                                  \r\n                                 \r\n                                    <dt lang=\"en\">Fit:</dt>\r\n                                    <dd>Oversize</dd>\r\n                                  \r\n                                 \r\n                                    <dt>Lavaggio:</dt>\r\n                                    <dd>Lavare a mano</dd>\r\n                                  \r\n                                 \r\n                                    <dt>Tipo di manica:</dt>\r\n                                    <dd>Corta</dd>\r\n                                  ', 'maglietta, cotone, personalizzata'),
(14, 'T-shirt Propped', 'M', 20, 't_shirt_propped', 'T-Shirt', 2, 'maglia con stampa dell’opera Propped', ' \r\n                                    <dt>Materiale:</dt>\r\n                                    <dd>Cotone</dd>\r\n                                  \r\n                                 \r\n                                    <dt lang=\"en\">Fit:</dt>\r\n                                    <dd>Oversize</dd>\r\n                                  \r\n                                 \r\n                                    <dt>Lavaggio:</dt>\r\n                                    <dd>Lavare a mano</dd>\r\n                                  \r\n                                 \r\n                                    <dt>Tipo di manica:</dt>\r\n                                    <dd>Corta</dd>\r\n                                  ', 'maglietta, cotone, personalizzata'),
(15, 'T-shirt Propped', 'L', 20, 't_shirt_propped', 'T-Shirt', 2, 'maglia con stampa dell’opera Propped', ' \r\n                                    <dt>Materiale:</dt>\r\n                                    <dd>Cotone</dd>\r\n                                  \r\n                                 \r\n                                    <dt lang=\"en\">Fit:</dt>\r\n                                    <dd>Oversize</dd>\r\n                                  \r\n                                 \r\n                                    <dt>Lavaggio:</dt>\r\n                                    <dd>Lavare a mano</dd>\r\n                                  \r\n                                 \r\n                                    <dt>Tipo di manica:</dt>\r\n                                    <dd>Corta</dd>\r\n                                  ', 'maglietta, cotone, personalizzata'),
(16, 'T-shirt Propped', 'XL', 20, 't_shirt_propped', 'T-Shirt', 2, 'maglia con stampa dell’opera Propped', ' \r\n                                    <dt>Materiale:</dt>\r\n                                    <dd>Cotone</dd>\r\n                                  \r\n                                 \r\n                                    <dt lang=\"en\">Fit:</dt>\r\n                                    <dd>Oversize</dd>\r\n                                  \r\n                                 \r\n                                    <dt>Lavaggio:</dt>\r\n                                    <dd>Lavare a mano</dd>\r\n                                  \r\n                                 \r\n                                    <dt>Tipo di manica:</dt>\r\n                                    <dd>Corta</dd>\r\n                                  ', 'maglietta, cotone, personalizzata'),
(17, 'T-shirt Migrants', 'XL', 20, 't_shirt_migrants', 'T-Shirt', 2, 'maglia con stampa dell’opera Migrants', ' \r\n                                    <dt>Materiale:</dt>\r\n                                    <dd>Cotone</dd>\r\n                                  \r\n                                 \r\n                                    <dt lang=\"en\">Fit:</dt>\r\n                                    <dd>Oversize</dd>\r\n                                  \r\n                                 \r\n                                    <dt>Lavaggio:</dt>\r\n                                    <dd>Lavare a mano</dd>\r\n                                  \r\n                                 \r\n                                    <dt>Tipo di manica:</dt>\r\n                                    <dd>Corta</dd>\r\n                                  ', 'maglietta, cotone, personalizzata'),
(18, 'Borraccia', NULL, 15, 'borraccia', 'basic', 0, 'borraccia bianca', ' \r\n                                    <dt>Materiale:</dt>\r\n                                    <dd>Acciaio</dd>\r\n                                  \r\n                                 \r\n                                    <dt lang=\"en\">Colore:</dt>\r\n                                    <dd>Bianco</dd>\r\n                                  \r\n                                 \r\n                                    <dt>Capacità:</dt>\r\n                                    <dd>500 <abbr title=\"millilitri\"> ml</abbr></dd>\r\n                                  \r\n                                 \r\n                                    <dt>Caratteristica speciale:</dt>\r\n                                    <dd>A prova di perdite</dd>\r\n                                  ', 'borraccia, acciaio'),
(19, 'Borraccia Migrants', 'U', 15, 'borraccia_migrants', 'Borraccia', 0, 'borraccia con stampa dell’opera Migrants', ' \r\n                                    <dt>Materiale:</dt>\r\n                                    <dd>Acciaio</dd>\r\n                                  \r\n                                 \r\n                                    <dt lang=\"en\">Colore:</dt>\r\n                                    <dd>Bianco</dd>\r\n                                  \r\n                                 \r\n                                    <dt>Capacità:</dt>\r\n                                    <dd>500 <abbr title=\"millilitri\"> ml</abbr></dd>\r\n                                  \r\n                                 \r\n                                    <dt>Caratteristica speciale:</dt>\r\n                                    <dd>A prova di perdite</dd>\r\n                                  ', 'borraccia, acciaio, personalizzata'),
(20, 'Borraccia Colors', 'U', 15, 'borraccia_colors', 'Borraccia', 0, 'borraccia con stampa dell’opera Colors', ' \r\n                                    <dt>Materiale:</dt>\r\n                                    <dd>Acciaio</dd>\r\n                                  \r\n                                 \r\n                                    <dt lang=\"en\">Colore:</dt>\r\n                                    <dd>Bianco</dd>\r\n                                  \r\n                                 \r\n                                    <dt>Capacità:</dt>\r\n                                    <dd>500 <abbr title=\"millilitri\"> ml</abbr></dd>\r\n                                  \r\n                                 \r\n                                    <dt>Caratteristica speciale:</dt>\r\n                                    <dd>A prova di perdite</dd>\r\n                                  ', 'borraccia, acciaio, personalizzata'),
(21, 'Borraccia Propped', 'U', 15, 'borraccia_propped', 'Borraccia', 0, 'borraccia con stampa dell’opera Propped', ' \r\n                                    <dt>Materiale:</dt>\r\n                                    <dd>Acciaio</dd>\r\n                                  \r\n                                 \r\n                                    <dt lang=\"en\">Colore:</dt>\r\n                                    <dd>Bianco</dd>\r\n                                  \r\n                                 \r\n                                    <dt>Capacità:</dt>\r\n                                    <dd>500 <abbr title=\"millilitri\"> ml</abbr></dd>\r\n                                  \r\n                                 \r\n                                    <dt>Caratteristica speciale:</dt>\r\n                                    <dd>A prova di perdite</dd>\r\n                                  ', 'borraccia, acciaio, personalizzata'),
(22, 'Borsa', NULL, 13, 'borsa', 'basic', 0, 'borsa di tela bianca', ' \r\n                                    <dt>Materiale:</dt>\r\n                                    <dd>Cotone</dd>\r\n                                  \r\n                                 \r\n                                    <dt lang=\"en\">Misura:</dt>\r\n                                    <dd>38<abbr title=\"per\"> x</abbr>42 <abbr title=\"centimetri\"> cm</abbr></dd>\r\n                                  \r\n                                 \r\n                                    <dt>Lavaggio:</dt>\r\n                                    <dd>Lavare a mano</dd>\r\n                                  \r\n                                 \r\n                                    <dt>Tipo di manica:</dt>\r\n                                    <dd>Corta</dd>\r\n                                  ', 'borsa, cotone'),
(23, 'Borsa Colors', 'U', 13, 'borsa_colors', 'Borsa', 0, 'borsa di tela con stampa dell’opera Colors', ' \r\n                                    <dt>Materiale:</dt>\r\n                                    <dd>Cotone</dd>\r\n                                  \r\n                                 \r\n                                    <dt lang=\"en\">Misura:</dt>\r\n                                    <dd>38<abbr title=\"per\"> x</abbr>42 <abbr title=\"centimetri\"> cm</abbr></dd>\r\n                                  \r\n                                 \r\n                                    <dt>Lavaggio:</dt>\r\n                                    <dd>Lavare a mano</dd>\r\n                                  \r\n                                 \r\n                                    <dt>Tipo di manica:</dt>\r\n                                    <dd>Corta</dd>\r\n                                  ', 'borsa, cotone, personalizzata'),
(24, 'Borsa Propped', 'U', 13, 'borsa_propped', 'Borsa', 0, 'borsa di tela con stampa dell’opera Propped', ' \r\n                                    <dt>Materiale:</dt>\r\n                                    <dd>Cotone</dd>\r\n                                  \r\n                                 \r\n                                    <dt lang=\"en\">Misura:</dt>\r\n                                    <dd>38<abbr title=\"per\"> x</abbr>42 <abbr title=\"centimetri\"> cm</abbr></dd>\r\n                                  \r\n                                 \r\n                                    <dt>Lavaggio:</dt>\r\n                                    <dd>Lavare a mano</dd>\r\n                                  \r\n                                 \r\n                                    <dt>Tipo di manica:</dt>\r\n                                    <dd>Corta</dd>\r\n                                  ', 'borsa, cotone, personalizzata'),
(25, 'Borsa Migrants', 'U', 13, 'borsa_migrants', 'Borsa', 0, 'borsa di tela con stampa dell’opera Migrants', ' \r\n                                    <dt>Materiale:</dt>\r\n                                    <dd>Cotone</dd>\r\n                                  \r\n                                 \r\n                                    <dt lang=\"en\">Misura:</dt>\r\n                                    <dd>38<abbr title=\"per\"> x</abbr>42 <abbr title=\"centimetri\"> cm</abbr></dd>\r\n                                  \r\n                                 \r\n                                    <dt>Lavaggio:</dt>\r\n                                    <dd>Lavare a mano</dd>\r\n                                  \r\n                                 \r\n                                    <dt>Tipo di manica:</dt>\r\n                                    <dd>Corta</dd>\r\n                                  ', 'borsa, cotone, personalizzata'),
(26, 'Poster', '', 22, 'poster', 'basic', 0, 'poster bianco', ' \r\n                                    <dt>Materiale:</dt>\r\n                                    <dd>Carta</dd>\r\n                                  \r\n                                 \r\n                                    <dt lang=\"en\">Dimensione:</dt>\r\n                                    <dd>90<abbr title=\"per\"> x</abbr>120 <abbr title=\"centimetri\"> cm</abbr></dd>\r\n                                  \r\n                                 \r\n                                    <dt>Bordo:</dt>\r\n                                    <dd>Bianco</dd>\r\n                                  \r\n                                 \r\n                                    <dt>Caratteristica speciale:</dt>\r\n                                    <dd>A prova di dissolvenza</dd>\r\n                                  ', 'poster, carta'),
(27, 'Poster Propped', 'U', 22, 'poster_propped', 'Poster', 0, 'poster con stampa di opera Propped', ' \r\n                                    <dt>Materiale:</dt>\r\n                                    <dd>Carta</dd>\r\n                                  \r\n                                 \r\n                                    <dt lang=\"en\">Dimensione:</dt>\r\n                                    <dd>90<abbr title=\"per\"> x</abbr>120 <abbr title=\"centimetri\"> cm</abbr></dd>\r\n                                  \r\n                                 \r\n                                    <dt>Bordo:</dt>\r\n                                    <dd>Bianco</dd>\r\n                                  \r\n                                 \r\n                                    <dt>Caratteristica speciale:</dt>\r\n                                    <dd>A prova di dissolvenza</dd>\r\n                                  ', 'poster, carta, personalizzato'),
(28, 'Poster Colors', 'U', 22, 'poster_colors', 'Poster', 0, 'poster con stampa di opera Colors', ' \r\n                                    <dt>Materiale:</dt>\r\n                                    <dd>Carta</dd>\r\n                                  \r\n                                 \r\n                                    <dt lang=\"en\">Dimensione:</dt>\r\n                                    <dd>90<abbr title=\"per\"> x</abbr>120 <abbr title=\"centimetri\"> cm</abbr></dd>\r\n                                  \r\n                                 \r\n                                    <dt>Bordo:</dt>\r\n                                    <dd>Bianco</dd>\r\n                                  \r\n                                 \r\n                                    <dt>Caratteristica speciale:</dt>\r\n                                    <dd>A prova di dissolvenza</dd>\r\n                                  ', 'poster, carta, personalizzato'),
(30, 'Agenda', '', 8, 'libro', 'basic', 0, 'agenda bianca', ' \r\n                                    <dt>Lingua:</dt>\r\n                                    <dd>Italiano</dd>\r\n                                  \r\n                                 \r\n                                    <dt lang=\"en\">Dimensione:</dt>\r\n                                    <dd>15<abbr title=\"per\"> x</abbr>21 <abbr title=\"centimetri\"> cm</abbr></dd>\r\n                                  \r\n                                 \r\n                                    <dt>Pagine:</dt>\r\n                                    <dd>136</dd>\r\n                                  \r\n                                 \r\n                                    <dt>Caratteristiche:</dt>\r\n                                    <dd>Agenda giornaliera</dd>\r\n                                  ', 'agenda, carta'),
(31, 'Agenda Colors', 'U', 8, 'libro_colors', 'Agenda', 0, 'agenda con stampa dell’opera Colors', ' \r\n                                    <dt>Lingua:</dt>\r\n                                    <dd>Italiano</dd>\r\n                                  \r\n                                 \r\n                                    <dt lang=\"en\">Dimensione:</dt>\r\n                                    <dd>15<abbr title=\"per\"> x</abbr>21 <abbr title=\"centimetri\"> cm</abbr></dd>\r\n                                  \r\n                                 \r\n                                    <dt>Pagine:</dt>\r\n                                    <dd>136</dd>\r\n                                  \r\n                                 \r\n                                    <dt>Caratteristiche:</dt>\r\n                                    <dd>Agenda giornaliera</dd>\r\n                                  ', 'agenda, carta, personalizzata'),
(32, 'Agenda Propped', 'U', 8, 'libro_propped', 'Agenda', 0, 'agenda con stampa dell’opera Propped', ' \r\n                                    <dt>Lingua:</dt>\r\n                                    <dd>Italiano</dd>\r\n                                  \r\n                                 \r\n                                    <dt lang=\"en\">Dimensione:</dt>\r\n                                    <dd>15<abbr title=\"per\"> x</abbr>21 <abbr title=\"centimetri\"> cm</abbr></dd>\r\n                                  \r\n                                 \r\n                                    <dt>Pagine:</dt>\r\n                                    <dd>136</dd>\r\n                                  \r\n                                 \r\n                                    <dt>Caratteristiche:</dt>\r\n                                    <dd>Agenda giornaliera</dd>\r\n                                  ', 'agenda, carta, personalizzata'),
(33, 'Agenda Migrants', 'U', 8, 'libro_migrants', 'Agenda', 0, 'agenda con stampa dell’opera Migrants', ' \r\n                                    <dt>Lingua:</dt>\r\n                                    <dd>Italiano</dd>\r\n                                  \r\n                                 \r\n                                    <dt lang=\"en\">Dimensione:</dt>\r\n                                    <dd>15<abbr title=\"per\"> x</abbr>21 <abbr title=\"centimetri\"> cm</abbr></dd>\r\n                                  \r\n                                 \r\n                                    <dt>Pagine:</dt>\r\n                                    <dd>136</dd>\r\n                                  \r\n                                 \r\n                                    <dt>Caratteristiche:</dt>\r\n                                    <dd>Agenda giornaliera</dd>\r\n                                  ', 'agenda, carta, personalizzata'),
(34, 'Poster Migrants', 'U', 22, 'poster_migrants', 'Poster', 0, 'poster con stampa di opera Migrants', ' \r\n                                    <dt>Materiale:</dt>\r\n                                    <dd>Carta</dd>\r\n                                  \r\n                                 \r\n                                    <dt lang=\"en\">Dimensione:</dt>\r\n                                    <dd>90<abbr title=\"per\"> x</abbr>120 <abbr title=\"centimetri\"> cm</abbr></dd>\r\n                                  \r\n                                 \r\n                                    <dt>Bordo:</dt>\r\n                                    <dd>Bianco</dd>\r\n                                  \r\n                                 \r\n                                    <dt>Caratteristica speciale:</dt>\r\n                                    <dd>A prova di dissolvenza</dd>\r\n                                  ', 'poster, carta, personalizzato');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `prodotto`
--
ALTER TABLE `prodotto`
  ADD PRIMARY KEY (`id_prodotto`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `prodotto`
--
ALTER TABLE `prodotto`
  MODIFY `id_prodotto` int(10) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=35;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
